[build]
builder = "NIXPACKS"
buildCommand = "npm config set cache /tmp/.npm-cache --global && npm ci && npm run build --workspace=@studyforge/api"

[deploy]
startCommand = "npm run start --workspace=@studyforge/api"
